---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: s3
spec:
  encryptedData:
    AWS_IMAGES_ACCESS: AgBpXGhOZTqY+iKNXATPe8g9b4IVDGxy6xRNP/CRHj6eeTsBkY9Lh+qjTOau7s8BDGc7pMBDGMBl7IN6X1Hf/X7jmwl8fxAMjmK0VbphNEsWjFnV/Tfm7Bq1ewF35OB+DLEjqMP50pOyHEFNR3YsPLXTYwNHJHWiYruqQpYwcTq6WDGTQ8qowuzL5EY8PWvKwigXevs3dC/tx+PHDUucwwa7+kguTfn71cy+SAyR39enEzqyoSqbssOmhV2Ct6ttjWSaTbuXFxqPHpZf+OieOMZeL8b+9uPMk+HAn/bc18Iz3XItnAZTra60Q/fAGdVGH4reqeyOLC9Vd2Mp6tT0M60+dJgjdPqEEblhIAteybcbR7RMWKg07TPgEc1TU+nuy4q5kUqlrNsW+PTZ9HIz4Z8F/4P1yyPgY4k9j6bMzCDFhPcPi7Y4eYJ/pZZCuw2UYo8hc7cnszv1XMTDZLs+XVNZMuJhwnAx/wZ/pxSGfHjU2irpsKZ887cphZmnC6K+Q43s6GCdkhR6a2qSGq9k6xNP9NMB1Ss6iWpClctlN4JEK18uKBQFsWSZKhi11KuWbVZTuH61aSWNUTGYOe6WD4ZSg0m8g53IgvD+tWH8rKv9iEQCEGCyhq88jhrxZMLphwTZDpV8iAUB+czf4FbyxDVdoeomnq/zeKjIUUJWb40nW+wc+hmgqEvi83y5beLjKuwKQlESBjMi63x8pYM60DlMJwk4qD5UYPF21W5KNaBLtA==
    AWS_IMAGES_SECRET: AgBsoTV2UwB+5lqfCuIkpvdPqgQRMv1yp8fd7Iweiu7En289iPB8vew8BTVqq5zLA5+nOZtdUkmTzA9/Uiq3hnkZ2eTInGHH6073Yc3cgOcK4WVl/cOslQTbRrLcKcVZpC5fDCe8dR2mf+RLbCG33qQQ1TXGyPr+mQM9oCPyvkzNt5+sIxwdgNJGp+so2Pf+aRfKEGrXFVecYRcoFChiSDJluD55sRtcujMf2iaczDT9TccX5cz8HbF+pf4GDh3OgvP8CJ4JPMI6R7JQs1+n8KYxL4KYu/Z/vSEdaiFNJHICLl9hLml9EceJDPzRhN0GnSB1nUpMETCf07t+CqhQlytXzO2qk9fxVZSkPLvivUx+/wT4y2rf777AMrWdU/W+SvppVdifn79UaPyGJg9Ozzg+LydhpRhMdUZraUAUe0F8pUvGV0ih2JoK+Pq4LqYUiKY1JwLOzBgYTwafc6IYZGOSjsEGQOvuOfjtm3KIJOtSU5ULo88/VEkZ7Q8A6C4P5DQYvfnShsICIkK9fecYfgWUTApNDFgit/OV45I+QYe0JEjZMi1EGCgG66vOmMsE390oe6TAFC9+jaSmsi4CfApFiaCKWLZR+5H5qIpZB7E4EarNc3P34HENWxJmWkROktM5zCjoUU1isq6x5WDD6BG3UuihqOdabE8HRvomA+RMB0vxV/7w1O+rTb5xu16gASCxFF8z2UFhJvkktKqO0M8RPAPTCUlzCwGIRW8RECwtog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: s3
    type: Opaque
