---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: backup-mysql-password
spec:
  encryptedData:
    password: AgCaZm3G6tvj3Jw9z7OKFT2f+Z59aIm9X23B8y6MvTAO1mIm5HmFuVjE3XHy8v3PhWm3ojJztXxBcoGMrRgOugpnwbKDOTa35QGch5Lvw+iQf/zeWrChizppszEtJn1UZZgCuEI8Pt64dg3ZNkbS3vMW0DzhlVfXOkLuO/81Q5a63YorCkyd5WB9rU1wCGvzFBbVQDa8AU59ezMelX4uaOjSNkQQDOepd1zKdZT6P6Pgb0qgJhik30EGTUkPNYz+cGZSiMlFBsGTnr0pWgdkF7deTYZL78sZD9kMrYyX4XPNa3BmEaOsy8k1+Fg1xevawRdxknilus0NPBO7eFCNgWuF9qwKKXRHruGG3Qt5d8jadM+iO0sOb69VKt4xsqL10YYrl3V47hclTmTJMsbrnox1/k3Km2F2BF23VVQZsbHb0cvHouJzLFn5vUfblqEGvhBewd8gTc7e4yXHvGABy87wdGRtfnfl84stbec2Tq7CRJ7ODOc8QercyDuBi+rUX53l6B7v3atBFnhpSLQ+WvYrw14D+/mqFAW3Mme8t27iR8LoQapGVKb2jRu5DjlQCUPNrMHaJdKLT9/88awkLhBn3EoO/j+5Ut5rqBfMrDLSDg6jBcHC8Rc5aDP/hgnuNYJgidkyTqPoxP8qzugMwm0zvn9lN8OxhU6C2y5YUCKbDRXr0/tuz7IExTICBJPGh3IISpUFfizRb3juB6+B+pjL0iX0cpzILsCWp8M4V9EY2r3Fdsyu/m6Lv1ggXTUPYJOJoXTEpb6mYzAGDzD8WqfQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: backup-mysql-password
    type: Opaque
